export const metadata = {
  title: "blog title",
  description: "Generated by create next app",
};
function BlogLayout({ children }) {
  return (
    <div>
      <header>Header</header>
      {children}
      <footer>Footer</footer>
    </div>
  );
}

export default BlogLayout;
